### PR TITLE
Added feature to show presence

### PR DESCRIPTION
**Pull request by calimonk**
Wanted to have the ability to change the color of a Luxafor based on your available/away status, we use it in the office to (automatically) show if you're available or not.

Added a new flag showStatus which is tied to that, while leaving old behaviour intact (mainly updated colors and added new colors).

### CODE REVIEW

**Comment by gpailler** [comment]
Hi @calimonk . Thanks for this PR. I tested it and it works fine! 
Please allow me some time to merge it as I have a refactoring in progress. I plan to release a new version in the coming weeks

**Comment by gpailler** [comment]
I merged the PR but I will just revert the ShowMention and ShowMessages to True

**Comment by calimonk** [comment]
Perfect, thanks!

**Comment by gpailler** [comment]
I'm wondering if the `SlackClient` class you created is mandatory because I still receive the PresenceChanged events without creating this second SlackClient instance and without sending the payload `presence_sub = 1`.
Do you remember if it was a test or if it's really useful?

**Comment by calimonk** [comment]
It's been a while since I've created it, so it could very well be that I changed things in the end and it's no longer needed. Let me look into it. 

There's a difference between setting yourself away and automatically going away as well though, so might be related to that, but I'll do a few tests.

**Comment by gpailler** [comment]
@calimonk I refactored the code to use a prerelease version of SlackApi to properly support presence.
Could you test the build available on https://ci.appveyor.com/project/gpailler/luxa4slack/builds/28852431/artifacts and confirm everything is working properly?

Thanks!

**Comment by calimonk** [comment]
Perfect, I'll give it a go!

**Pull request merged**
